Include reference to exactextractr
Robinlovelace/geocompr pull request #821
Opened 2022-06-28 22:09 UTC by Lvulis

This is draft text which resolves Issue #813. I am sensitive to the style conflicts that arise with documents written by multiple authors that have contrasting vision, so please feel free to edit or rework as you see fit.

Specific edits are:
- Add paragraph in chapter 6
- Add bonus question in Chapter 6 (should add a solution then?)

2022-06-29 09:56 UTC, Robinlovelace requested changes
Looking good, minor changes requested.

2022-06-29 09:56 UTC, Robinlovelace commented on 06-raster-vector.Rmd
> +Although the `terra` package offers rapid extraction of raster values within polygons, the `extract()` can still be a bottleneck when processing large polygon datasets. The `exactextractr` package of
Looks good but please switch to sentence-based line breaks. See our style guide for further info.

2022-06-29 09:56 UTC, Robinlovelace commented on 06-raster-vector.Rmd
> +By default, it is `FALSE` as this operation requires more computations. The `exact_extract()` function always computes the covrage fraction of the polygon in each cell.
Typo in here: covrage

2022-06-29 15:28 UTC, Lvulis commented
Fixed and also fixed the font for the package names.

2022-07-02 12:57 UTC, Robinlovelace commented
Nudge on this @Nowosad, I think this is good to merge.

2022-07-02 13:01 UTC, Nowosad commented
@Robinlovelace -- I remember about this. I will try to find some time to read it carefully tomorrow or on Monday.

2022-07-02 13:05 UTC, Robinlovelace commented
> @Robinlovelace -- I remember about this. I will try to find some time to read it carefully tomorrow or on Monday.

:+1:

2022-07-03 14:55 UTC, Nowosad commented
@Lvulis great additions! 

And, yes -- please add an exercise solution.

2022-07-07 19:12 UTC, Lvulis commented
@Nowosad Should I make a separate PR in the solutions to add to the solution? I wrote up the following one, there is extra formatting inside to get it to match the output of **`terra`**.  Also, I am not too familiar with the best way to do PRs, I merged upstream changes into my fork to make sure merge conflicts don't start to arise, if anything should be undone please let me know :)

```R
zion_points_buf_2 = exactextractr::exact_extract(x = srtm, 
                                         y = zion_buffer)
# Make output similar to terra::extract() 
zion_points_buf_2 = lapply(seq_along(zion_points_buf_2), \(i) cbind(ID = i,
                                                                    zion_points_buf_2[[i]]))


zion_points_buf_2 = do.call(rbind, zion_points_buf_2) 
zion_points_buf_2 = rename(zion_points_buf_2, srtm = value)

plot(zion_points_points$srtm, zion_points_buf_2$srtm2)
```

2022-07-08 08:09 UTC, Nowosad commented
@Lvulis you can add a solution to this PR if that is not a problem for you. If it is -- feel free to open a new one;)

2022-07-08 15:17 UTC, Nowosad commented
Read https://geocompr.github.io/post/2022/geocompr-solutions/ if you want to learn more about our exercises/solution setup (any improvement ideas are welcomed).

2022-07-08 15:17 UTC, merged